language: node_js
node_js:
  - "6.8.1"
branches:
  only:
  - master
  - develop
deploy:
  provider: script
  skip_cleanup: true
  script: .travis/deploy.sh
  on:
    all_branches: true
addons:
  ssh_known_hosts: ldso.diogomoura.me